#! /usr/bin/env bash
exec /home/ddraig/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0xf198b10 .scope module, "bcd_to_bin_TB" "bcd_to_bin_TB" 2 3;
 .timescale -9 -12;
P_0xf17ce20 .param/real "DUTY_CYCLE" 0 2 22, Cr<m4000000000000000gfc1>; value=0.500000
P_0xf17ce60 .param/l "OFFSET" 0 2 23, +C4<00000000000000000000000000000000>;
P_0xf17cea0 .param/l "PERIOD" 0 2 21, +C4<00000000000000000000000000010100>;
v0xf1c8800_0 .var "clk", 0 0;
v0xf1c8950_0 .net "done", 0 0, v0xf1c5dc0_0;  1 drivers
v0xf1c8a10_0 .var "i", 20 0;
v0xf1c8ab0_0 .var "in_data", 7 0;
v0xf1c8bc0_0 .var "reset", 0 0;
v0xf1c8cd0_0 .net "result", 7 0, L_0xf1c8fb0;  1 drivers
v0xf1c8de0_0 .var "rst", 0 0;
v0xf1c8f10_0 .var "start", 0 0;
E_0xf195a10 .event "reset_trigger";
E_0xf1a8720 .event "reset_done_trigger";
S_0xf198d90 .scope begin, "TEST_CASE" "TEST_CASE" 2 94, 2 94 0, S_0xf198b10;
 .timescale -9 -12;
S_0xf146140 .scope module, "uut" "bcd_to_bin" 2 12, 3 1 0, S_0xf198b10;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "init";
    .port_info 3 /INPUT 8 "in_data";
    .port_info 4 /OUTPUT 8 "result";
    .port_info 5 /OUTPUT 1 "done";
v0xf1c7d40_0 .net "clk", 0 0, v0xf1c8800_0;  1 drivers
v0xf1c7e00_0 .net "done", 0 0, v0xf1c5dc0_0;  alias, 1 drivers
v0xf1c7ec0_0 .net "in_data", 7 0, v0xf1c8ab0_0;  1 drivers
v0xf1c7f90_0 .net "init", 0 0, v0xf1c8f10_0;  1 drivers
v0xf1c8060_0 .net "result", 7 0, L_0xf1c8fb0;  alias, 1 drivers
v0xf1c8100_0 .net "rst", 0 0, v0xf1c8de0_0;  1 drivers
v0xf1c81a0_0 .net "w_ld_acc", 0 0, v0xf1c5f20_0;  1 drivers
v0xf1c8290_0 .net "w_load", 0 0, v0xf1c5fe0_0;  1 drivers
v0xf1c8330_0 .net "w_r0", 15 0, v0xf1c76b0_0;  1 drivers
v0xf1c8460_0 .net "w_sh", 0 0, v0xf1c61b0_0;  1 drivers
v0xf1c8500_0 .net "w_sub_high", 3 0, L_0xf1a5670;  1 drivers
v0xf1c85a0_0 .net "w_sub_low", 3 0, L_0xf1a5aa0;  1 drivers
v0xf1c8690_0 .net "w_z", 0 0, L_0xf1c93a0;  1 drivers
L_0xf1c90e0 .part v0xf1c76b0_0, 12, 4;
L_0xf1c91a0 .part v0xf1c76b0_0, 8, 4;
S_0xf146320 .scope module, "comp_high" "comp_bin" 3 31, 4 1 0, S_0xf146140;
 .timescale 0 0;
    .port_info 0 /INPUT 4 "nibble_in";
    .port_info 1 /OUTPUT 4 "nibble_out";
L_0xf1a5670 .functor BUFZ 4, v0xf1a63f0_0, C4<0000>, C4<0000>, C4<0000>;
v0xf1a5780_0 .net "nibble_in", 3 0, L_0xf1c90e0;  1 drivers
v0xf1a5b90_0 .net "nibble_out", 3 0, L_0xf1a5670;  alias, 1 drivers
v0xf1a63f0_0 .var "tmp", 3 0;
E_0xf1a8760 .event anyedge, v0xf1a5780_0;
S_0xf1c5310 .scope module, "comp_low" "comp_bin" 3 36, 4 1 0, S_0xf146140;
 .timescale 0 0;
    .port_info 0 /INPUT 4 "nibble_in";
    .port_info 1 /OUTPUT 4 "nibble_out";
L_0xf1a5aa0 .functor BUFZ 4, v0xf1a7830_0, C4<0000>, C4<0000>, C4<0000>;
v0xf1a6bc0_0 .net "nibble_in", 3 0, L_0xf1c91a0;  1 drivers
v0xf1a6fd0_0 .net "nibble_out", 3 0, L_0xf1a5aa0;  alias, 1 drivers
v0xf1a7830_0 .var "tmp", 3 0;
E_0xf1c5540 .event anyedge, v0xf1a6bc0_0;
S_0xf1c56e0 .scope module, "control0" "control_bin" 3 50, 5 1 0, S_0xf146140;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "init";
    .port_info 3 /INPUT 1 "z";
    .port_info 4 /OUTPUT 1 "done";
    .port_info 5 /OUTPUT 1 "sh";
    .port_info 6 /OUTPUT 1 "load";
    .port_info 7 /OUTPUT 1 "ld_acc";
P_0xf1c58c0 .param/l "ACC" 0 5 16, C4<100>;
P_0xf1c5900 .param/l "CHECK1" 0 5 14, C4<010>;
P_0xf1c5940 .param/l "CHECK2" 0 5 15, C4<011>;
P_0xf1c5980 .param/l "END_ST" 0 5 17, C4<101>;
P_0xf1c59c0 .param/l "SHIFT" 0 5 13, C4<001>;
P_0xf1c5a00 .param/l "START" 0 5 12, C4<000>;
v0xf1748d0_0 .net "clk", 0 0, v0xf1c8800_0;  alias, 1 drivers
v0xf1c5dc0_0 .var "done", 0 0;
v0xf1c5e80_0 .net "init", 0 0, v0xf1c8f10_0;  alias, 1 drivers
v0xf1c5f20_0 .var "ld_acc", 0 0;
v0xf1c5fe0_0 .var "load", 0 0;
v0xf1c60f0_0 .net "rst", 0 0, v0xf1c8de0_0;  alias, 1 drivers
v0xf1c61b0_0 .var "sh", 0 0;
v0xf1c6270_0 .var "state", 2 0;
v0xf1c6350_0 .net "z", 0 0, L_0xf1c93a0;  alias, 1 drivers
E_0xf1c5d20 .event posedge, v0xf1748d0_0;
S_0xf1c6510 .scope module, "counter0" "counter_bin" 3 41, 6 1 0, S_0xf146140;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "load";
    .port_info 3 /INPUT 1 "dec";
    .port_info 4 /OUTPUT 4 "count";
    .port_info 5 /OUTPUT 1 "z";
L_0x7121fad26018 .functor BUFT 1, C4<0000>, C4<0>, C4<0>, C4<0>;
v0xf1c6760_0 .net/2u *"_ivl_0", 3 0, L_0x7121fad26018;  1 drivers
v0xf1c6860_0 .net *"_ivl_2", 0 0, L_0xf1c92d0;  1 drivers
L_0x7121fad26060 .functor BUFT 1, C4<1>, C4<0>, C4<0>, C4<0>;
v0xf1c6920_0 .net/2u *"_ivl_4", 0 0, L_0x7121fad26060;  1 drivers
L_0x7121fad260a8 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0xf1c69e0_0 .net/2u *"_ivl_6", 0 0, L_0x7121fad260a8;  1 drivers
v0xf1c6ac0_0 .net "clk", 0 0, v0xf1c8800_0;  alias, 1 drivers
v0xf1c6bb0_0 .var "count", 3 0;
v0xf1c6c70_0 .net "dec", 0 0, v0xf1c61b0_0;  alias, 1 drivers
v0xf1c6d10_0 .net "load", 0 0, v0xf1c5fe0_0;  alias, 1 drivers
v0xf1c6de0_0 .net "rst", 0 0, v0xf1c8de0_0;  alias, 1 drivers
v0xf1c6eb0_0 .net "z", 0 0, L_0xf1c93a0;  alias, 1 drivers
E_0xf1c66e0 .event negedge, v0xf1748d0_0;
L_0xf1c92d0 .cmp/eq 4, v0xf1c6bb0_0, L_0x7121fad26018;
L_0xf1c93a0 .functor MUXZ 1, L_0x7121fad260a8, L_0x7121fad26060, L_0xf1c92d0, C4<>;
S_0xf1c7000 .scope module, "rsr0" "rsr_bin" 3 18, 7 1 0, S_0xf146140;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "load";
    .port_info 3 /INPUT 1 "shift";
    .port_info 4 /INPUT 1 "ld_acc";
    .port_info 5 /INPUT 8 "in_data";
    .port_info 6 /INPUT 4 "sub_high";
    .port_info 7 /INPUT 4 "sub_low";
    .port_info 8 /OUTPUT 16 "r0";
    .port_info 9 /OUTPUT 8 "result";
v0xf1c7330_0 .net "clk", 0 0, v0xf1c8800_0;  alias, 1 drivers
v0xf1c7440_0 .net "in_data", 7 0, v0xf1c8ab0_0;  alias, 1 drivers
v0xf1c7520_0 .net "ld_acc", 0 0, v0xf1c5f20_0;  alias, 1 drivers
v0xf1c75c0_0 .net "load", 0 0, v0xf1c5fe0_0;  alias, 1 drivers
v0xf1c76b0_0 .var "r0", 15 0;
v0xf1c77a0_0 .net "result", 7 0, L_0xf1c8fb0;  alias, 1 drivers
v0xf1c7880_0 .net "rst", 0 0, v0xf1c8de0_0;  alias, 1 drivers
v0xf1c7970_0 .net "shift", 0 0, v0xf1c61b0_0;  alias, 1 drivers
v0xf1c7a60_0 .net "sub_high", 3 0, L_0xf1a5670;  alias, 1 drivers
v0xf1c7b20_0 .net "sub_low", 3 0, L_0xf1a5aa0;  alias, 1 drivers
L_0xf1c8fb0 .part v0xf1c76b0_0, 0, 8;
    .scope S_0xf1c7000;
T_0 ;
    %wait E_0xf1c66e0;
    %load/vec4 v0xf1c7880_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0xf1c76b0_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0xf1c75c0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %load/vec4 v0xf1c7440_0;
    %concati/vec4 0, 0, 8;
    %assign/vec4 v0xf1c76b0_0, 0;
    %jmp T_0.3;
T_0.2 ;
    %load/vec4 v0xf1c7970_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.4, 8;
    %load/vec4 v0xf1c76b0_0;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %shiftr 4;
    %assign/vec4 v0xf1c76b0_0, 0;
    %jmp T_0.5;
T_0.4 ;
    %load/vec4 v0xf1c7520_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.6, 8;
    %load/vec4 v0xf1c7a60_0;
    %load/vec4 v0xf1c7b20_0;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0xf1c76b0_0;
    %parti/s 8, 0, 2;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0xf1c76b0_0, 0;
    %jmp T_0.7;
T_0.6 ;
    %load/vec4 v0xf1c76b0_0;
    %assign/vec4 v0xf1c76b0_0, 0;
T_0.7 ;
T_0.5 ;
T_0.3 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0xf146320;
T_1 ;
    %wait E_0xf1a8760;
    %load/vec4 v0xf1a5780_0;
    %cmpi/u 8, 0, 4;
    %flag_inv 5; GE is !LT
    %jmp/0xz  T_1.0, 5;
    %load/vec4 v0xf1a5780_0;
    %subi 3, 0, 4;
    %store/vec4 v0xf1a63f0_0, 0, 4;
    %jmp T_1.1;
T_1.0 ;
    %load/vec4 v0xf1a5780_0;
    %store/vec4 v0xf1a63f0_0, 0, 4;
T_1.1 ;
    %jmp T_1;
    .thread T_1, $push;
    .scope S_0xf1c5310;
T_2 ;
    %wait E_0xf1c5540;
    %load/vec4 v0xf1a6bc0_0;
    %cmpi/u 8, 0, 4;
    %flag_inv 5; GE is !LT
    %jmp/0xz  T_2.0, 5;
    %load/vec4 v0xf1a6bc0_0;
    %subi 3, 0, 4;
    %store/vec4 v0xf1a7830_0, 0, 4;
    %jmp T_2.1;
T_2.0 ;
    %load/vec4 v0xf1a6bc0_0;
    %store/vec4 v0xf1a7830_0, 0, 4;
T_2.1 ;
    %jmp T_2;
    .thread T_2, $push;
    .scope S_0xf1c6510;
T_3 ;
    %wait E_0xf1c66e0;
    %load/vec4 v0xf1c6de0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.0, 8;
    %pushi/vec4 8, 0, 4;
    %assign/vec4 v0xf1c6bb0_0, 0;
    %jmp T_3.1;
T_3.0 ;
    %load/vec4 v0xf1c6d10_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.2, 8;
    %pushi/vec4 8, 0, 4;
    %assign/vec4 v0xf1c6bb0_0, 0;
    %jmp T_3.3;
T_3.2 ;
    %load/vec4 v0xf1c6c70_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_3.4, 8;
    %load/vec4 v0xf1c6bb0_0;
    %subi 1, 0, 4;
    %assign/vec4 v0xf1c6bb0_0, 0;
    %jmp T_3.5;
T_3.4 ;
    %load/vec4 v0xf1c6bb0_0;
    %assign/vec4 v0xf1c6bb0_0, 0;
T_3.5 ;
T_3.3 ;
T_3.1 ;
    %jmp T_3;
    .thread T_3;
    .scope S_0xf1c56e0;
T_4 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c5dc0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c61b0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c5fe0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c5f20_0, 0, 1;
    %pushi/vec4 0, 0, 3;
    %store/vec4 v0xf1c6270_0, 0, 3;
    %end;
    .thread T_4;
    .scope S_0xf1c56e0;
T_5 ;
    %wait E_0xf1c5d20;
    %load/vec4 v0xf1c60f0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.0, 8;
    %pushi/vec4 0, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %jmp T_5.1;
T_5.0 ;
    %load/vec4 v0xf1c6270_0;
    %dup/vec4;
    %pushi/vec4 0, 0, 3;
    %cmp/u;
    %jmp/1 T_5.2, 6;
    %dup/vec4;
    %pushi/vec4 1, 0, 3;
    %cmp/u;
    %jmp/1 T_5.3, 6;
    %dup/vec4;
    %pushi/vec4 2, 0, 3;
    %cmp/u;
    %jmp/1 T_5.4, 6;
    %dup/vec4;
    %pushi/vec4 3, 0, 3;
    %cmp/u;
    %jmp/1 T_5.5, 6;
    %dup/vec4;
    %pushi/vec4 4, 0, 3;
    %cmp/u;
    %jmp/1 T_5.6, 6;
    %dup/vec4;
    %pushi/vec4 5, 0, 3;
    %cmp/u;
    %jmp/1 T_5.7, 6;
    %pushi/vec4 0, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.9;
T_5.2 ;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %load/vec4 v0xf1c5e80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.10, 8;
    %pushi/vec4 1, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 1, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.11;
T_5.10 ;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 0, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
T_5.11 ;
    %jmp T_5.9;
T_5.3 ;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 1, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %load/vec4 v0xf1c6350_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.12, 8;
    %pushi/vec4 5, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.13;
T_5.12 ;
    %pushi/vec4 2, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
T_5.13 ;
    %jmp T_5.9;
T_5.4 ;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %load/vec4 v0xf1c6350_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.14, 8;
    %pushi/vec4 5, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.15;
T_5.14 ;
    %pushi/vec4 3, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
T_5.15 ;
    %jmp T_5.9;
T_5.5 ;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 1, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %pushi/vec4 4, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.9;
T_5.6 ;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %pushi/vec4 1, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.9;
T_5.7 ;
    %pushi/vec4 1, 0, 1;
    %assign/vec4 v0xf1c5dc0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c61b0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 0, 0, 1;
    %assign/vec4 v0xf1c5f20_0, 0;
    %load/vec4 v0xf1c5e80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_5.16, 8;
    %pushi/vec4 1, 0, 1;
    %assign/vec4 v0xf1c5fe0_0, 0;
    %pushi/vec4 1, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
    %jmp T_5.17;
T_5.16 ;
    %pushi/vec4 5, 0, 3;
    %assign/vec4 v0xf1c6270_0, 0;
T_5.17 ;
    %jmp T_5.9;
T_5.9 ;
    %pop/vec4 1;
T_5.1 ;
    %jmp T_5;
    .thread T_5;
    .scope S_0xf198b10;
T_6 ;
T_6.0 ;
    %wait E_0xf195a10;
    %wait E_0xf1c66e0;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xf1c8de0_0, 0, 1;
    %wait E_0xf1c66e0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8de0_0, 0, 1;
    %event E_0xf1a8720;
    %jmp T_6.0;
T_6.1 ;
    %end;
    .thread T_6;
    .scope S_0xf198b10;
T_7 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8800_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xf1c8bc0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 69, 0, 8;
    %store/vec4 v0xf1c8ab0_0, 0, 8;
    %end;
    .thread T_7;
    .scope S_0xf198b10;
T_8 ;
    %delay 0, 0;
T_8.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8800_0, 0, 1;
    %delay 10000, 0;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xf1c8800_0, 0, 1;
    %delay 10000, 0;
    %jmp T_8.0;
T_8.1 ;
    %end;
    .thread T_8;
    .scope S_0xf198b10;
T_9 ;
    %delay 10000, 0;
    %event E_0xf195a10;
    %wait E_0xf1a8720;
    %wait E_0xf1c5d20;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %wait E_0xf1c5d20;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 0, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
T_9.0 ; Top of for-loop 
    %load/vec4 v0xf1c8a10_0;
    %pad/u 32;
    %cmpi/u 2, 0, 32;
    %jmp/0xz T_9.1, 5;
    %wait E_0xf1c5d20;
T_9.2 ; for-loop step statement
    %load/vec4 v0xf1c8a10_0;
    %addi 1, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
    %jmp T_9.0;
T_9.1 ; for-loop exit label
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 0, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
T_9.3 ; Top of for-loop 
    %load/vec4 v0xf1c8a10_0;
    %pad/u 32;
    %cmpi/u 40, 0, 32;
    %jmp/0xz T_9.4, 5;
    %wait E_0xf1c5d20;
T_9.5 ; for-loop step statement
    %load/vec4 v0xf1c8a10_0;
    %addi 1, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
    %jmp T_9.3;
T_9.4 ; for-loop exit label
    %pushi/vec4 120, 0, 8;
    %store/vec4 v0xf1c8ab0_0, 0, 8;
    %wait E_0xf1c5d20;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 0, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
T_9.6 ; Top of for-loop 
    %load/vec4 v0xf1c8a10_0;
    %pad/u 32;
    %cmpi/u 2, 0, 32;
    %jmp/0xz T_9.7, 5;
    %wait E_0xf1c5d20;
T_9.8 ; for-loop step statement
    %load/vec4 v0xf1c8a10_0;
    %addi 1, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
    %jmp T_9.6;
T_9.7 ; for-loop exit label
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 0, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
T_9.9 ; Top of for-loop 
    %load/vec4 v0xf1c8a10_0;
    %pad/u 32;
    %cmpi/u 40, 0, 32;
    %jmp/0xz T_9.10, 5;
    %wait E_0xf1c5d20;
T_9.11 ; for-loop step statement
    %load/vec4 v0xf1c8a10_0;
    %addi 1, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
    %jmp T_9.9;
T_9.10 ; for-loop exit label
    %pushi/vec4 153, 0, 8;
    %store/vec4 v0xf1c8ab0_0, 0, 8;
    %wait E_0xf1c5d20;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 0, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
T_9.12 ; Top of for-loop 
    %load/vec4 v0xf1c8a10_0;
    %pad/u 32;
    %cmpi/u 2, 0, 32;
    %jmp/0xz T_9.13, 5;
    %wait E_0xf1c5d20;
T_9.14 ; for-loop step statement
    %load/vec4 v0xf1c8a10_0;
    %addi 1, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
    %jmp T_9.12;
T_9.13 ; for-loop exit label
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0xf1c8f10_0, 0, 1;
    %pushi/vec4 0, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
T_9.15 ; Top of for-loop 
    %load/vec4 v0xf1c8a10_0;
    %pad/u 32;
    %cmpi/u 40, 0, 32;
    %jmp/0xz T_9.16, 5;
    %wait E_0xf1c5d20;
T_9.17 ; for-loop step statement
    %load/vec4 v0xf1c8a10_0;
    %addi 1, 0, 21;
    %store/vec4 v0xf1c8a10_0, 0, 21;
    %jmp T_9.15;
T_9.16 ; for-loop exit label
    %end;
    .thread T_9;
    .scope S_0xf198b10;
T_10 ;
    %fork t_1, S_0xf198d90;
    %jmp t_0;
    .scope S_0xf198d90;
t_1 ;
    %vpi_call 2 95 "$dumpfile", "bcd_to_bin_TB.vcd" {0 0 0};
    %vpi_call 2 96 "$dumpvars", 32'sb11111111111111111111111111111111, S_0xf146140 {0 0 0};
    %delay 2500000, 0;
    %vpi_call 2 97 "$finish" {0 0 0};
    %end;
    .scope S_0xf198b10;
t_0 %join;
    %end;
    .thread T_10;
# The file index is used to find the file name in the following table.
:file_names 8;
    "N/A";
    "<interactive>";
    "bcd_to_bin_TB.v";
    "bcd_to_bin.v";
    "comp_bin.v";
    "control_bin.v";
    "counter_bin.v";
    "rsr_bin.v";
# EOF
