#! /usr/bin/env bash
exec /home/ddraig/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x338ea4d0 .scope module, "rsr_bin_TB" "rsr_bin_TB" 2 3;
 .timescale -9 -12;
v0x33906ea0_0 .var "clk", 0 0;
v0x33906f60_0 .var "in_data", 7 0;
v0x33907000_0 .var "ld_acc", 0 0;
v0x33907100_0 .var "load", 0 0;
v0x339071d0_0 .net "r0", 15 0, v0x339067b0_0;  1 drivers
v0x33907270_0 .net "result", 7 0, L_0x33907710;  1 drivers
v0x33907340_0 .var "rst", 0 0;
v0x33907410_0 .var "shift", 0 0;
v0x339074e0_0 .var "sub_high", 3 0;
v0x33907640_0 .var "sub_low", 3 0;
S_0x338ea660 .scope module, "uut" "rsr_bin" 2 15, 3 1 0, S_0x338ea4d0;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "load";
    .port_info 3 /INPUT 1 "shift";
    .port_info 4 /INPUT 1 "ld_acc";
    .port_info 5 /INPUT 8 "in_data";
    .port_info 6 /INPUT 4 "sub_high";
    .port_info 7 /INPUT 4 "sub_low";
    .port_info 8 /OUTPUT 16 "r0";
    .port_info 9 /OUTPUT 8 "result";
v0x338ad2b0_0 .net "clk", 0 0, v0x33906ea0_0;  1 drivers
v0x33906570_0 .net "in_data", 7 0, v0x33906f60_0;  1 drivers
v0x33906650_0 .net "ld_acc", 0 0, v0x33907000_0;  1 drivers
v0x339066f0_0 .net "load", 0 0, v0x33907100_0;  1 drivers
v0x339067b0_0 .var "r0", 15 0;
v0x339068e0_0 .net "result", 7 0, L_0x33907710;  alias, 1 drivers
v0x339069c0_0 .net "rst", 0 0, v0x33907340_0;  1 drivers
v0x33906a80_0 .net "shift", 0 0, v0x33907410_0;  1 drivers
v0x33906b40_0 .net "sub_high", 3 0, v0x339074e0_0;  1 drivers
v0x33906c20_0 .net "sub_low", 3 0, v0x33907640_0;  1 drivers
E_0x338e74f0 .event negedge, v0x338ad2b0_0;
L_0x33907710 .part v0x339067b0_0, 0, 8;
    .scope S_0x338ea660;
T_0 ;
    %wait E_0x338e74f0;
    %load/vec4 v0x339069c0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x339067b0_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x339066f0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %load/vec4 v0x33906570_0;
    %concati/vec4 0, 0, 8;
    %assign/vec4 v0x339067b0_0, 0;
    %jmp T_0.3;
T_0.2 ;
    %load/vec4 v0x33906a80_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.4, 8;
    %load/vec4 v0x339067b0_0;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %shiftr 4;
    %assign/vec4 v0x339067b0_0, 0;
    %jmp T_0.5;
T_0.4 ;
    %load/vec4 v0x33906650_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.6, 8;
    %load/vec4 v0x33906b40_0;
    %load/vec4 v0x33906c20_0;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x339067b0_0;
    %parti/s 8, 0, 2;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0x339067b0_0, 0;
    %jmp T_0.7;
T_0.6 ;
    %load/vec4 v0x339067b0_0;
    %assign/vec4 v0x339067b0_0, 0;
T_0.7 ;
T_0.5 ;
T_0.3 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0x338ea4d0;
T_1 ;
    %delay 10000, 0;
    %load/vec4 v0x33906ea0_0;
    %inv;
    %store/vec4 v0x33906ea0_0, 0, 1;
    %jmp T_1;
    .thread T_1;
    .scope S_0x338ea4d0;
T_2 ;
    %vpi_call 2 31 "$dumpfile", "TB/rsr_bin_TB.vcd" {0 0 0};
    %vpi_call 2 32 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x338ea4d0 {0 0 0};
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33906ea0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x33907340_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907100_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907410_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907000_0, 0, 1;
    %pushi/vec4 69, 0, 8;
    %store/vec4 v0x33906f60_0, 0, 8;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x339074e0_0, 0, 4;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x33907640_0, 0, 4;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907340_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x33907100_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907100_0, 0, 1;
    %load/vec4 v0x339071d0_0;
    %cmpi/ne 17664, 0, 16;
    %jmp/0xz  T_2.0, 6;
    %vpi_call 2 42 "$display", "rsr_bin_TB FAIL en Carga: Esperado=16'h4500, Obtenido=%h", v0x339071d0_0 {0 0 0};
    %vpi_call 2 42 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.0 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x33907410_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907410_0, 0, 1;
    %load/vec4 v0x339071d0_0;
    %cmpi/ne 8832, 0, 16;
    %jmp/0xz  T_2.2, 6;
    %vpi_call 2 48 "$display", "rsr_bin_TB FAIL en Desplazamiento: Esperado=16'h2280, Obtenido=%h", v0x339071d0_0 {0 0 0};
    %vpi_call 2 48 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.2 ;
    %pushi/vec4 7, 0, 4;
    %store/vec4 v0x339074e0_0, 0, 4;
    %pushi/vec4 2, 0, 4;
    %store/vec4 v0x33907640_0, 0, 4;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x33907000_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x33907000_0, 0, 1;
    %load/vec4 v0x339071d0_0;
    %cmpi/ne 29312, 0, 16;
    %jmp/1 T_2.6, 6;
    %flag_mov 8, 6;
    %load/vec4 v0x33907270_0;
    %cmpi/ne 128, 0, 8;
    %flag_or 6, 8;
T_2.6;
    %jmp/0xz  T_2.4, 6;
    %vpi_call 2 56 "$display", "rsr_bin_TB FAIL en ld_acc: Esperado r0=16'h7280, Obtenido r0=%h", v0x339071d0_0 {0 0 0};
    %vpi_call 2 56 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.4 ;
    %vpi_call 2 59 "$display", "rsr_bin_TB PASS" {0 0 0};
    %vpi_call 2 60 "$finish" {0 0 0};
    %end;
    .thread T_2;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "TB/rsr_bin_TB.v";
    "rsr_bin.v";
# EOF
