#! /usr/bin/env bash
exec /home/ddraig/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x365704d0 .scope module, "lsr_bcd_TB" "lsr_bcd_TB" 2 3;
 .timescale -9 -12;
v0x3658ce70_0 .var "add_high", 3 0;
v0x3658cf50_0 .var "add_low", 3 0;
v0x3658cff0_0 .var "clk", 0 0;
v0x3658d0f0_0 .var "in_data", 7 0;
v0x3658d1c0_0 .var "ld_acc", 0 0;
v0x3658d260_0 .var "load", 0 0;
v0x3658d330_0 .net "r0", 15 0, v0x3658c990_0;  1 drivers
v0x3658d400_0 .net "result", 7 0, L_0x3658d700;  1 drivers
v0x3658d4d0_0 .var "rst", 0 0;
v0x3658d630_0 .var "shift", 0 0;
S_0x36570660 .scope module, "uut" "lsr_bcd" 2 16, 3 1 0, S_0x365704d0;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "load";
    .port_info 3 /INPUT 1 "shift";
    .port_info 4 /INPUT 1 "ld_acc";
    .port_info 5 /INPUT 8 "in_data";
    .port_info 6 /INPUT 4 "add_high";
    .port_info 7 /INPUT 4 "add_low";
    .port_info 8 /OUTPUT 16 "r0";
    .port_info 9 /OUTPUT 8 "result";
v0x365332b0_0 .net "add_high", 3 0, v0x3658ce70_0;  1 drivers
v0x3658c560_0 .net "add_low", 3 0, v0x3658cf50_0;  1 drivers
v0x3658c640_0 .net "clk", 0 0, v0x3658cff0_0;  1 drivers
v0x3658c6e0_0 .net "in_data", 7 0, v0x3658d0f0_0;  1 drivers
v0x3658c7c0_0 .net "ld_acc", 0 0, v0x3658d1c0_0;  1 drivers
v0x3658c8d0_0 .net "load", 0 0, v0x3658d260_0;  1 drivers
v0x3658c990_0 .var "r0", 15 0;
v0x3658ca70_0 .net "result", 7 0, L_0x3658d700;  alias, 1 drivers
v0x3658cb50_0 .net "rst", 0 0, v0x3658d4d0_0;  1 drivers
v0x3658cc10_0 .net "shift", 0 0, v0x3658d630_0;  1 drivers
E_0x3656c370 .event negedge, v0x3658c640_0;
L_0x3658d700 .part v0x3658c990_0, 8, 8;
    .scope S_0x36570660;
T_0 ;
    %wait E_0x3656c370;
    %load/vec4 v0x3658cb50_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 0, 0, 16;
    %assign/vec4 v0x3658c990_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x3658c8d0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %pushi/vec4 0, 0, 8;
    %load/vec4 v0x3658c6e0_0;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0x3658c990_0, 0;
    %jmp T_0.3;
T_0.2 ;
    %load/vec4 v0x3658cc10_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.4, 8;
    %load/vec4 v0x3658c990_0;
    %ix/load 4, 1, 0;
    %flag_set/imm 4, 0;
    %shiftl 4;
    %assign/vec4 v0x3658c990_0, 0;
    %jmp T_0.5;
T_0.4 ;
    %load/vec4 v0x3658c7c0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.6, 8;
    %load/vec4 v0x365332b0_0;
    %load/vec4 v0x3658c560_0;
    %concat/vec4; draw_concat_vec4
    %load/vec4 v0x3658c990_0;
    %parti/s 8, 0, 2;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0x3658c990_0, 0;
    %jmp T_0.7;
T_0.6 ;
    %load/vec4 v0x3658c990_0;
    %assign/vec4 v0x3658c990_0, 0;
T_0.7 ;
T_0.5 ;
T_0.3 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0x365704d0;
T_1 ;
    %delay 10000, 0;
    %load/vec4 v0x3658cff0_0;
    %inv;
    %store/vec4 v0x3658cff0_0, 0, 1;
    %jmp T_1;
    .thread T_1;
    .scope S_0x365704d0;
T_2 ;
    %vpi_call 2 32 "$dumpfile", "TB/lsr_bcd_TB.vcd" {0 0 0};
    %vpi_call 2 33 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x365704d0 {0 0 0};
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658cff0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x3658d4d0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d260_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d630_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d1c0_0, 0, 1;
    %pushi/vec4 165, 0, 8;
    %store/vec4 v0x3658d0f0_0, 0, 8;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x3658ce70_0, 0, 4;
    %pushi/vec4 0, 0, 4;
    %store/vec4 v0x3658cf50_0, 0, 4;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d4d0_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x3658d260_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d260_0, 0, 1;
    %load/vec4 v0x3658d330_0;
    %parti/s 8, 0, 2;
    %cmpi/ne 165, 0, 8;
    %jmp/0xz  T_2.0, 6;
    %vpi_call 2 43 "$display", "lsr_bcd_TB FAIL en carga de dato. Obtenido: %h", v0x3658d330_0 {0 0 0};
    %vpi_call 2 43 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.0 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x3658d630_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d630_0, 0, 1;
    %load/vec4 v0x3658d330_0;
    %cmpi/ne 330, 0, 16;
    %jmp/0xz  T_2.2, 6;
    %vpi_call 2 49 "$display", "lsr_bcd_TB FAIL en desplazamiento. Obtenido: %h", v0x3658d330_0 {0 0 0};
    %vpi_call 2 49 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.2 ;
    %pushi/vec4 8, 0, 4;
    %store/vec4 v0x3658ce70_0, 0, 4;
    %pushi/vec4 3, 0, 4;
    %store/vec4 v0x3658cf50_0, 0, 4;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x3658d1c0_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x3658d1c0_0, 0, 1;
    %load/vec4 v0x3658d400_0;
    %cmpi/ne 131, 0, 8;
    %jmp/1 T_2.6, 6;
    %flag_mov 8, 6;
    %load/vec4 v0x3658d330_0;
    %cmpi/ne 33610, 0, 16;
    %flag_or 6, 8;
T_2.6;
    %jmp/0xz  T_2.4, 6;
    %vpi_call 2 57 "$display", "lsr_bcd_TB FAIL en carga de nibbles BCD. Obtenido: result=%h, r0=%h", v0x3658d400_0, v0x3658d330_0 {0 0 0};
    %vpi_call 2 57 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.4 ;
    %vpi_call 2 60 "$display", "lsr_bcd_TB PASS" {0 0 0};
    %vpi_call 2 61 "$finish" {0 0 0};
    %end;
    .thread T_2;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "TB/lsr_bcd_TB.v";
    "lsr_bcd.v";
# EOF
