#! /usr/bin/env bash
exec /home/ddraig/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/ddraig/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x2a7cc8b0 .scope module, "counter_bcd_TB" "counter_bcd_TB" 2 3;
 .timescale -9 -12;
v0x2a7e5470_0 .var "clk", 0 0;
v0x2a7e5530_0 .net "count", 3 0, v0x2a7e4fd0_0;  1 drivers
v0x2a7e55d0_0 .var "dec", 0 0;
v0x2a7e56a0_0 .var "load", 0 0;
v0x2a7e5770_0 .var "rst", 0 0;
v0x2a7e5810_0 .net "z", 0 0, L_0x2a7e5ab0;  1 drivers
S_0x2a7cca40 .scope module, "uut" "counter_bcd" 2 11, 3 1 0, S_0x2a7cc8b0;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "rst";
    .port_info 2 /INPUT 1 "load";
    .port_info 3 /INPUT 1 "dec";
    .port_info 4 /OUTPUT 4 "count";
    .port_info 5 /OUTPUT 1 "z";
L_0x74c5ad49c018 .functor BUFT 1, C4<0000>, C4<0>, C4<0>, C4<0>;
v0x2a7bb070_0 .net/2u *"_ivl_0", 3 0, L_0x74c5ad49c018;  1 drivers
v0x2a7bb890_0 .net *"_ivl_2", 0 0, L_0x2a7e5910;  1 drivers
L_0x74c5ad49c060 .functor BUFT 1, C4<1>, C4<0>, C4<0>, C4<0>;
v0x2a7bb930_0 .net/2u *"_ivl_4", 0 0, L_0x74c5ad49c060;  1 drivers
L_0x74c5ad49c0a8 .functor BUFT 1, C4<0>, C4<0>, C4<0>, C4<0>;
v0x2a7e4de0_0 .net/2u *"_ivl_6", 0 0, L_0x74c5ad49c0a8;  1 drivers
v0x2a7e4ec0_0 .net "clk", 0 0, v0x2a7e5470_0;  1 drivers
v0x2a7e4fd0_0 .var "count", 3 0;
v0x2a7e50b0_0 .net "dec", 0 0, v0x2a7e55d0_0;  1 drivers
v0x2a7e5170_0 .net "load", 0 0, v0x2a7e56a0_0;  1 drivers
v0x2a7e5230_0 .net "rst", 0 0, v0x2a7e5770_0;  1 drivers
v0x2a7e52f0_0 .net "z", 0 0, L_0x2a7e5ab0;  alias, 1 drivers
E_0x2a7ca800 .event negedge, v0x2a7e4ec0_0;
L_0x2a7e5910 .cmp/eq 4, v0x2a7e4fd0_0, L_0x74c5ad49c018;
L_0x2a7e5ab0 .functor MUXZ 1, L_0x74c5ad49c0a8, L_0x74c5ad49c060, L_0x2a7e5910, C4<>;
    .scope S_0x2a7cca40;
T_0 ;
    %wait E_0x2a7ca800;
    %load/vec4 v0x2a7e5230_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 8, 0, 4;
    %assign/vec4 v0x2a7e4fd0_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x2a7e5170_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %pushi/vec4 8, 0, 4;
    %assign/vec4 v0x2a7e4fd0_0, 0;
    %jmp T_0.3;
T_0.2 ;
    %load/vec4 v0x2a7e50b0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.4, 8;
    %load/vec4 v0x2a7e4fd0_0;
    %subi 1, 0, 4;
    %assign/vec4 v0x2a7e4fd0_0, 0;
    %jmp T_0.5;
T_0.4 ;
    %load/vec4 v0x2a7e4fd0_0;
    %assign/vec4 v0x2a7e4fd0_0, 0;
T_0.5 ;
T_0.3 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0x2a7cc8b0;
T_1 ;
    %delay 10000, 0;
    %load/vec4 v0x2a7e5470_0;
    %inv;
    %store/vec4 v0x2a7e5470_0, 0, 1;
    %jmp T_1;
    .thread T_1;
    .scope S_0x2a7cc8b0;
T_2 ;
    %vpi_call 2 23 "$dumpfile", "TB/counter_bcd_TB.vcd" {0 0 0};
    %vpi_call 2 24 "$dumpvars", 32'sb00000000000000000000000000000000, S_0x2a7cc8b0 {0 0 0};
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2a7e5470_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2a7e5770_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2a7e56a0_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2a7e55d0_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2a7e5770_0, 0, 1;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2a7e56a0_0, 0, 1;
    %delay 20000, 0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2a7e56a0_0, 0, 1;
    %load/vec4 v0x2a7e5530_0;
    %cmpi/ne 8, 0, 4;
    %jmp/1 T_2.2, 6;
    %flag_mov 8, 6;
    %load/vec4 v0x2a7e5810_0;
    %cmpi/ne 0, 0, 1;
    %flag_or 6, 8;
T_2.2;
    %jmp/0xz  T_2.0, 6;
    %vpi_call 2 32 "$display", "counter_bcd_TB FAIL en carga inicial" {0 0 0};
    %vpi_call 2 32 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.0 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x2a7e55d0_0, 0, 1;
    %pushi/vec4 8, 0, 32;
T_2.3 %dup/vec4;
    %pushi/vec4 0, 0, 32;
    %cmp/s;
    %jmp/1xz T_2.4, 5;
    %jmp/1 T_2.4, 4;
    %pushi/vec4 1, 0, 32;
    %sub;
    %wait E_0x2a7ca800;
    %jmp T_2.3;
T_2.4 ;
    %pop/vec4 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x2a7e55d0_0, 0, 1;
    %load/vec4 v0x2a7e5530_0;
    %cmpi/ne 0, 0, 4;
    %jmp/1 T_2.7, 6;
    %flag_mov 8, 6;
    %load/vec4 v0x2a7e5810_0;
    %cmpi/ne 1, 0, 1;
    %flag_or 6, 8;
T_2.7;
    %jmp/0xz  T_2.5, 6;
    %vpi_call 2 41 "$display", "counter_bcd_TB FAIL: No alcanz\303\263 el cero correctamente. count=%d, z=%b", v0x2a7e5530_0, v0x2a7e5810_0 {0 0 0};
    %vpi_call 2 42 "$fatal", 32'sb00000000000000000000000000000001 {0 0 0};
T_2.5 ;
    %vpi_call 2 45 "$display", "counter_bcd_TB PASS" {0 0 0};
    %vpi_call 2 46 "$finish" {0 0 0};
    %end;
    .thread T_2;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "TB/counter_bcd_TB.v";
    "counter_bcd.v";
# EOF
